### create a flight booking
POST localhost:7788/api/v1/flight-bookings
Content-Type: application/json

{
    "userId" : 1234,

    "flightNumber" : "AA144"

}

### find all flight bookings
GET localhost:7788/api/v1/flight-bookings

